### ISSUE TITLE
Update Joe's email address to `jde1@st-andrews.ac.uk`

### ISSUE THREAD

**Issue by Joseph-Edwards** [semigroups/Semigroups#1001]
In the list of contributors, my email address is cited as `je53@st-andrews.ac.uk`. This should be `jde1@st-andrews.ac.uk`. From what I can tell, these are the places with issues:
https://github.com/semigroups/Semigroups/blob/ebcaf4a9621ac0cf6c6590b3a4fc246a1b96abc9/.mailmap#L6
https://github.com/semigroups/Semigroups/blob/ebcaf4a9621ac0cf6c6590b3a4fc246a1b96abc9/PackageInfo.g#L120

**Comment by james-d-mitchell** [comment]
Thanks @Joseph-Edwards and sorry!
