### ISSUE TITLE
Remove references to removed file 'gap/tools/enums.gi'

### ISSUE THREAD

**Issue by ChrisJefferson** [semigroups/Semigroups#1022]
The file `gap/tools/enums.gi` was removed at some point, but semigroups still tries to load it.

At the moment, this does nothing (which is why it wasn't noticed), but we'd like to make this a loud warning in future, so it would be good to clean it up.

**Comment by fingolfin** [comment]
This was resolved by PR #1025 in July. Any estimate when a new semigroups release might be made containing this fix?
