### ISSUE TITLE
Constructor for Clifford semigroups

### ISSUE THREAD

**Issue by ChristopherRussell** [semigroups/Semigroups#528]
(Feature request)

A function which returns a clifford semigroup when given as input, in some way, a semilattice; a list of groups `G` (one for each vertex of the semilattice digraph); and list of homomorphism (one for each edge of the semilattice digraph) such that the homomorphism corresponding to edge `[i, j]` is a homomorphism between `G[i]` and `G[j]`.

Such a function may be quite difficult to use since specifying the homomorphism seems awkward. One way to make it a little simpler would be to only specify homomorphism for edges in the `DigraphTransitiveReflexiveReduction` of the semilattice digraph.

The clifford semigroup could be returned as it's own object or as a partial perm semigroup.

**Comment by flsmith** [comment]
Implemented in https://github.com/gap-packages/Digraphs/pull/161

**Comment by wilfwilson** [comment]
Does that mean this issue can be closed?

**Comment by flsmith** [comment]
Sure!
