### ISSUE TITLE
Coset monoids

### ISSUE THREAD

**Issue by The-Beast** [semigroups/Semigroups#675]
This is a feature request/suggestion, for creating coset monoids.

Given a group G, one can form the coset monoid C(G).  This is a (factorisable) inverse monoid.  As a set, C(G) consists of all cosets of all subgroups of G.  The product of two cosets Ag * Bh is defined to be the smallest coset containing the union of Ag and Bh.  In symbols, Ag * Bh = (A \vee gBg^{-1})gh.  Here \vee is the join of subgroups (so A \vee B is the subgroup generated by the union of A and B).

**Comment by le27** [comment]
Hello, the easiest way for us to make the coset monoid of a group is to represent it as a transformation monoid. However this approach is unlikely to be usable on very large examples. Do you know what kind of sizes of groups you would like to make coset monoids for? Do you know what you would like to be able to compute about them?

**Comment by james-d-mitchell** [comment]
@The-Beast

**Comment by The-Beast** [comment]
Sorry, forgot to reply earlier.  It actually isn't a pressing need, but it occurred to me it would be a neat thing to compute with.  I was just thinking of some basic computations - eggbox diagrams, congruence lattices, maximal subsemigroups, etc.  If there isn't an obvious/simple way to create them, please don't worry about it!

**Comment by james-d-mitchell** [comment]
Thanks @The-Beast, @le27 already made a preliminary implementation in PR #692, it works, but as @le27 says, we weren't sure if you had something specific in mind and if what's in PR #692 is sufficient for your needs.
