### ISSUE TITLE
prerequisites.sh may error if libsemigroups already present

### ISSUE THREAD

**Issue by mtorpey** [semigroups/Semigroups#702]
When installing Semigroups 3.3.1 with PackageManager, by archive, the following error gets reported:
```
-e libsemigroups v1.0.6 is required by this version of Semigroups
-e the /home/mtorpey/.gap/pkg/semigroups-3.3.1/libsemigroups directory exists and is non-empty
-e The installed version of libsemigroups is v1.0.6
/home/mtorpey/.gap/pkg/semigroups-3.3.1/prerequisites.sh: 25: [: 1.0.6: unexpected operator
-e Error, the installed version of libsemigroups is too old
```
This seems to be caused by `prerequisites.sh` being called while a version of libsermigroups is already present (bundled in the Semigroups archive).  It looks like `prerequisites.sh:25` is maybe unsafe bash syntax, but I can never remember how this works.

Any idea what's happening here?

**Comment by james-d-mitchell** [comment]
Thanks @mtorpey I'm pretty sure we can fix this!

**Comment by james-d-mitchell** [comment]
I think this is resolved now @mtorpey and @wilfwilson
