### ISSUE TITLE
Semigroups package website not up to date

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#715]
The Semigroup package website https://semigroups.github.io/Semigroups lists 3.3.1 as the most recent release, but 3.4.0 is.

**Comment by james-d-mitchell** [comment]
Thanks @wilfwilson i noticed this too, not sure what’s going on, will investigate tomorrow

**Comment by james-d-mitchell** [comment]
I think I just forgot to push to the `gh-pages` branch after making a release, I think the website is up to date now.
