### ISSUE TITLE
Enable the manual to be compiled without loading the package

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#745]
See https://github.com/gap-system/ReleaseTools/issues/74

We should probably use `GAPDocManualLabFromSixFile` instead of `GAPDocManualLab` in `makedoc.g`.

We might also want to investigate using `AutoDoc` to compile the package (and possibly investigate whether there are some AutoDoc features we might like to use...)

**Comment by fingolfin** [comment]
To quite myself from that issue: Something like GAPDocManualLabFromSixFile("Semigroups", "doc/manual.six"); ought to do the trick. (Untested!)

**Comment by wilfwilson** [comment]
Actually I'll make a new issue, it's different.

**Comment by james-d-mitchell** [comment]
Oh, I see, I think I misunderstood the meaning of the issue, my bad! Happy to reopen this, or have a new issue. Thanks! @wilfwilson
