### ISSUE TITLE
Tests on Windows can't write to the 'pkg/semigroups' directory

### ISSUE THREAD

**Issue by ChrisJefferson** [semigroups/Semigroups#747]
On windows, the semigroups tests fail because we install GAP for all users, which means GAP cannot write into the 'pkg/semigroups' directory.

The fix (I believe) is to look through the tests for all cases where data is written (mostly calls to WriteGenerators), and call "DirectoryTemporary" to make a temp directory to store any new files in. This will have the advantage that the directory, and files, will be automatically cleaned up when GAP exits.

**Comment by james-d-mitchell** [comment]
Thanks @ChrisJefferson, I'll try to resolve this in the next release.

**Comment by james-d-mitchell** [comment]
@ChrisJefferson I think I've resolved this, but can't test it. If the issue is restricted to not being able to write to the semigroups package directory, then I think I've fixed it. If there are also problems reading from files in the same directory, then there's probably more work to do...

**Comment by ChrisJefferson** [comment]
So, the tests work fine, but there is an unrelated problem in semigroups 4 which I'll make a new issue about.

**Comment by james-d-mitchell** [comment]
@ChrisJefferson is it ok to close this?

**Comment by ChrisJefferson** [comment]
yep fixed
