### ISSUE TITLE
AssignGeneratorVariables for fp semigroups

### ISSUE THREAD

**Issue by tomcontileslie** [semigroups/Semigroups#758]
This is a feature request. Currently in `/gap/semigroups/semifp.gi` there are methods to `AssignGeneratorVariables` for a free semigroup and for a free monoid. Would it not also be of interest to be able to do:
```
gap> f := FreeSemigroup("a", "b");
<free semigroup on the generators [ a, b ]>
gap> AssignGeneratorVariables(f);
#I  Assigned the global variables [ a, b ]
gap> s := f / [[a * b, b * a]];
<fp semigroup on the generators [ a, b ]>
gap> AssignGeneratorVariables(s);  # this is the requested feature
#I  Something something...
gap> a * b = b * a;
true
```
I guess this would overwrite the previously assigned free semigroup variables `a` and `b`. But then again, at least based on my experience, if you're assigning generator variables for a free semigroup then creating an fp semigroup, there is little use for the original variables once you've got the fp semigroup, so this doesn't seem unreasonable.

**Comment by james-d-mitchell** [comment]
Thanks @tomcontileslie that's a great suggestion, I'm vaguely surprised that this isn't implemented already! I don't think this will be difficult to do either so we should certainly do it!

**Comment by tomcontileslie** [comment]
That's great @james-d-mitchell, I'm very happy to sort that issue out myself if you'd like? Just wanted to check first if everyone found it reasonable!
