### ISSUE TITLE
Improve how `\mathscr{L}` etc looks in the non-MathJax HTML manual

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#783]
This looks particularly bad for `DotString` https://semigroups.github.io/Semigroups/doc/chap19.html#X7F51F3CD7E13D199:
<img width="693" alt="Screenshot 2021-05-20 at 20 09 12" src="https://user-images.githubusercontent.com/8956868/119035392-6e87c280-b9a7-11eb-89e9-c68a9b096922.png">

I think we just need better fallbacks for the these latex entities.
While we're at it, we should check for similar weirdness in the non-MathJax version.

**Comment by james-d-mitchell** [comment]
Good point, is it possible to distinguish in GAPdoc between when Mathjax is on and off?

**Comment by wilfwilson** [comment]
I'm 99% there's a way to specify a fallback in GAPDoc, I just can't remember how to do it right now.

**Comment by chinmayanagpal** [comment]
@wilfwilson  http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc/doc/chap3.html#X7A0D26B180BEDE37 is this it?

**Comment by wilfwilson** [comment]
Yes I think so!
