### ISSUE TITLE
Rename Michael Torpey to Michael Young and update his URL

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#793]
@mtorpey would like to be credited/named in this package as Michael Young.

He would also like his URL to be updated from https://mtorpey.github.io to https://mct25.host.cs.st-andrews.ac.uk

**Comment by Joseph-Edwards** [comment]
Do we want to change all instances of Torpey to Young (excluding things like email addresses)?

For example, in `doc/title.xml` there is a section that reads

>[...] the Engineering and Physical Sciences Research Council (EPSRC) for funding the PhD scholarship of M. Torpey when he worked on this project (EP/M506631/1).

Should this stay as Torpey, since that is the name under which the funding was awarded?

**Comment by mtorpey** [comment]
I'd suggest changing it everywhere -- if anyone really cares about that particular EPSRC grant, the code is there anyway, so I'm sure they'd work it out.  And this way it's clear that it's all one author, definitely me.

The exception, as you mention, is email address and Github username - I'll still be `mct25@` and @mtorpey.

**Comment by Joseph-Edwards** [comment]
Makes sense - I can implement that now.
