### ISSUE TITLE
Missing method for `MeetSemigroupCongruences` for GIS congruences

### ISSUE THREAD

**Issue by james-d-mitchell** [semigroups/Semigroups#814]
The title says it all, there could be a method for `MeetSemigroupCongruences` for graph inverse semigroup congruences (GIS), but there isn't.

**Comment by marinaanagno** [comment]
@james-d-mitchell  Sure, sorry it wasn't needed for the computation on the lattice and completely forgot! Will put that in my TODO list :)

**Comment by james-d-mitchell** [comment]
Resolved in v4.0.3
