### ISSUE TITLE
trying to  load semigroups under gap-4.12.0

### ISSUE THREAD

**Issue by cdwensley** [semigroups/Semigroups#864]
Compilation of the version supplied with gap-4.12.0 seems to have been OK (./configure & make): 
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in libsemigroups
make[2]: Nothing to be done for `all'.
./cnf/install-sh -c -d ./bin/x86_64-apple-darwin17-default64-kv8
rm -f /Applications/gap/gap-4.12.0/pkg/semigroups/bin/x86_64-apple-darwin17-default64-kv8/semigroups.so  # workaround for macOS code signing
cp .libs/semigroups.so /Applications/gap/gap-4.12.0/pkg/semigroups/bin/x86_64-apple-darwin17-default64-kv8/semigroups.so
SUCCESS!

But when running LoadPackage("semigroups") in GAP the required packages appear to load OK and then: 
Error, LOAD_DYN: failed to load kernel module /Applications/gap/gap-4.12.0/pkg/semigr\
oups/bin/x86_64-apple-darwin17-default64-kv8/semigroups.so, dlopen(/Applicatio\
ns/gap/gap-4.12.0/pkg/semigroups/bin/x86_64-apple-darwin17-default64-kv8/semig\
roups.so, 5): Library not loaded: /Applications/gap/gap4r12/pkg/semigroups/lib\
semigroups/../bin/lib/libsemigroups.2.dylib
  Referenced from: /Applications/gap/gap-4.12.0/pkg/semigroups/bin/x86_64-appl\
e-darwin17-default64-kv8/semigroups.so
  Reason: image not found in
  LOAD_DYN( filename ) at /Applications/gap/gap-4.12.0/lib/files.gd:592 called from 
<function "LoadDynamicModule">( <arguments> )
 called from read-eval loop at /Applications/gap/gap-4.12.0/pkg/semigroups/init.g:22
Error, was not in any namespace at /Applications/gap/gap-4.12.0/lib/variable.g:269 called from
LEAVE_NAMESPACE(  ); at /Applications/gap/gap-4.12.0/lib/package.gi:1325 called from
ReadPackage( pkgname, "init.g" 
 ); at /Applications/gap/gap-4.12.0/lib/package.gi:1686 called from
<function "LoadPackage">( <arguments> )
 called from read-eval loop at *stdin*:1
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>

I've no idea what this means.  Any suggestions?

**Comment by james-d-mitchell** [comment]
Looks like you are trying to install the development version, if I’m not mistaken. The pasted output from configure and make is suspiciously short, it doesn’t look like anything was actually compiled, do you have the correct version of libsemigroups? And perhaps trying doing ‘make distclean’ then ‘./autogen.sh’ and then recompiling.

**Comment by cdwensley** [comment]
I'm definitely trying to install the version supplied on Friday in gap-4.12.0/pkg/semigroups/ 
Sorry - forgotten about 'make disclean'.  
./autgen.sh fails with: 
Christopher-Wensleys-iMac:semigroups christopherwensley$ ./autogen.sh 
++ dirname ./autogen.sh
+ autoreconf -vif .
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory 

Not sure about the libsemigroups version.  './configure' ends with: 
=== configuring in libsemigroups (/Applications/gap/gap-4.12.0/pkg/semigroups/libsemigroups)
configure: WARNING: no configuration information is in libsemigroups
and then make fails: 
Christopher-Wensleys-iMac:semigroups christopherwensley$ make
/Library/Developer/CommandLineTools/usr/bin/make -C libsemigroups install
make[1]: *** No rule to make target `install'.  Stop.
make: *** [bin/include/libsemigroups/libsemigroups.hpp] Error 2

I do not find the semigroups README.md very clear on the subject of libsemigroups. 
It _appears_ from the README that it is included with the semigroups package, but maybe that's not the case? 
I have just downloaded libsemigroups-2.2.1.tar.gz; gunzipped and 'tar xvf'd it, which ended with: 
tar: Error exit delayed from previous errors.
But to install this, looking at: https://libsemigroups.readthedocs.io/en/latest/install.html, 
I see "This installation method assumes that you have anaconda or miniconda installed." 
So this is all getting far too complicated, and not what I would expect when installing a GAP package. 

I initially found the problem when Loading XMod which requires groupoids which suggests semigroups. 
If problems persist I shall drop the suggestion from groupoids. 
Meanwhile, I shall try downloading semigroups-5.0.2 from github and see where that gets me.

**Comment by cdwensley** [comment]
Success!  After reloading semigroups-5.0.2 from GitHub, everything worked as it should. 
I wonder whether running gap-4.12.0/bin/BuildPackages.sh, which failed to compile semigroups, might have caused changes to some of the semigroups files, which then caused ./configure + make to fail later. 
More likely, I did something to upset some of the files. 
Sorry for the noise!

**Comment by cdwensley** [comment]
The benefit of all this for me is that I have realised that I need to say something in XMod's and groupoids' READMEs about the various needed and suggested packages (including Semigroups) and which ones need to be compiled.
