### ISSUE TITLE
semigroups lacks `--disable-hpcombi`

### ISSUE THREAD

**Issue by jengelh** [semigroups/Semigroups#895]
libsemigroups/m4/ax_check_hpcombi.m4 has a `AC_ARG_ENABLE([hpcombi]` block, but (semigroups)/m4/ax_check_hpcombi.m4 does not, so semigroups itself still tries to use `-march=avx` (#894) / `-mavx` and there is no way to disable it. I suppose copying the m4 file from libsemigroups to semigroups might address the issue.

**Comment by james-d-mitchell** [comment]
Thanks for the report, I'll try to fix this asap. The situation is probably exasperated since I am no longer developing on any x86 computers that `HpCombi` requires, and so this has probably rotted to some extent.

**Comment by james-d-mitchell** [comment]
I think this is now resolved, there's some discussion in #897 about whether or not this is the case.

**Comment by james-d-mitchell** [comment]
Resolved in v5.2.0
