### ISSUE TITLE
Release packages ship with outdated version 2.3.2 of libsemigroups

### ISSUE THREAD

**Issue by rawrunprotected** [semigroups/Semigroups#968]
Noticed this while investigating possible performance issues working with a rather large semigroup.

The external version for libsemigroups in https://github.com/semigroups/Semigroups/blob/main/.LIBSEMIGROUPS_VERSION is currently set to 2.3.2. This release of libsemigroups is lacking some at least one fix critical for performance that is ironically enough fixed for the version directly included in Semigroups: https://github.com/libsemigroups/libsemigroups/pull/418 only made it into https://github.com/libsemigroups/libsemigroups/tree/v2.4.1. As a result, current releases of the Semigroups package, and by transitivity current releases of gap, will likely leave quite a bit of performance on the table.

I would have liked to open a PR myself to bump the version, but I wasn't able to successfully build Semigroups locally for testing yet.

**Comment by james-d-mitchell** [comment]
Good point, this should be simple to resolve. I'll try to bump the version and make a new release tomorrow. If you're having any issues with building Semigroups feel free to post another issue or add something here

**Comment by james-d-mitchell** [comment]
Resolved by #969, I'll start the release process now too.

**Comment by james-d-mitchell** [comment]
Hopefully resolved in v5.3.3.
